apiVersion: v1
data:
  ca.crt: |
    -----BEGIN CERTIFICATE-----
    MIIDBjCCAe6gAwIBAgIBATANBgkqhkiG9w0BAQsFADAVMRMwEQYDVQQDEwptaW5p
    a3ViZUNBMB4XDTIzMDgyNzA3MTgyNFoXDTMzMDgyNTA3MTgyNFowFTETMBEGA1UE
    AxMKbWluaWt1YmVDQTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAMDY
    Dm7YJSKrfZ2AgXNZYs6uJXmI0j5aSfw1kpGXfqS2DV8IzqJn0vdFQ62pns/HEzxv
    Ir2uMoFYCpDo9u1Or7L4/Tj6YtAJz2zXppRPDzWGFrYJAh24JKGOvFoGRJJ2X7M2
    H47atyCmV1JRlW81wzTrxiERZJCepOwr3F/hJc+tatQ2/hCssokexK+PeeSquEUD
    YonXMl1nUdj4ieWRV/iMLvrJTtQB5yz//AUtw+NoMK2yZhfzscIAGczmq1YVt8hF
    GCLX5XpLgZ/6x5rnDBt32RakeqiYdOm2vqyphB5uLJcLkbGuhz2F3jLWqOzjt4K+
    j5lbsyobVfG2G9lIMjECAwEAAaNhMF8wDgYDVR0PAQH/BAQDAgKkMB0GA1UdJQQW
    MBQGCCsGAQUFBwMCBggrBgEFBQcDATAPBgNVHRMBAf8EBTADAQH/MB0GA1UdDgQW
    BBSkidXVD+XqRpER4AQolByOBr5R4TANBgkqhkiG9w0BAQsFAAOCAQEAWX0kf9Q4
    sE8bGGEdnjFmA4clwLIvxz+3TpB/FgYON2Yple+wLg7Dx4Z7LdO0aQl097IxzBOa
    Rkzi8z9hP0YIkgYYLq4kraxiqfac0T+MwsHQacnMT1sgWq2KcWQ7LCLTwF1lngzW
    vUWrZ/fcJNyIRN0Qf7LL8DkuIQPxXifOaStQnDETtrpQIzTfX+mRWXNOmBed4U7N
    LgHhdCQ1gDmcQUFLvCs8Wr5xTRsngrNWvpGu86nG6LNeUtdxkVjiboia2JFI+Nji
    BVyavoiKOF5EDji5CVkEqkKJb/F3+M2v1IEFWWhpn3yZaOSIa/H0L2ujpw6Nl61S
    lwnkfOVkgnZGcA==
    -----END CERTIFICATE-----
kind: ConfigMap
metadata:
  annotations:
    kubernetes.io/description: Contains a CA bundle that can be used to verify the
      kube-apiserver when using internal endpoints such as the internal service IP
      or kubernetes.default.svc. No other usage is guaranteed across distributions
      of Kubernetes clusters.
  creationTimestamp: "2023-09-01T13:06:28Z"
  name: kube-root-ca.crt
  namespace: default
